"""Luxury bar chart renderer skill with 4 stunning visual styles."""

from __future__ import annotations

from typing import Any

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, Ellipse, PathPatch
from matplotlib.path import Path
import numpy as np
from scipy.ndimage import gaussian_filter

from neo_legend.models import RenderRequest, RenderResult
from neo_legend._plotting import (
    add_canvas,
    add_reference_footer,
    cmap_color,
    create_figure,
    make_gradient,
    save_png,
    seeded_rng,
)
from neo_legend.base import BaseLegendSkill, StyleDefinition


class BarChartSkill(BaseLegendSkill):
    legend_type = "bar_chart"
    display_name = "Luxury Bar Chart"
    default_style = "glass_3d"
    default_size = (1179, 1454)
    style_definitions = (
        StyleDefinition(
            "glass_3d",
            "Glass-texture 3D bar chart with rounded bars, shadows and highlights.",
        ),
        StyleDefinition(
            "neon_tubes",
            "Neon glow tube effect bar chart with multi-layer glowing borders.",
        ),
        StyleDefinition(
            "gradient_sky",
            "Sky-gradient sunset-themed bar chart with per-bar independent gradients.",
        ),
        StyleDefinition(
            "crystal_pillars",
            "Crystal pillar bar chart with refraction texture and golden labels.",
        ),
    )

    _DEFAULT_PALETTE = [
        "#ff6b6b",
        "#4ecdc4",
        "#45b7d1",
        "#96ceb4",
        "#ffeaa7",
        "#dfe6e9",
        "#fd79a8",
        "#a29bfe",
        "#6c5ce7",
        "#00cec9",
    ]

    _NEON_PALETTE = ["#ff006e", "#8338ec", "#3a86ff", "#06ffa5", "#ffbe0b"]

    _SUNSET_PALETTES = [
        ["#ff6b6b", "#ee5a24"],
        ["#feca57", "#ff9f43"],
        ["#48dbfb", "#0abde3"],
        ["#1dd1a1", "#10ac84"],
        ["#5f27cd", "#341f97"],
    ]

    def render(self, request: RenderRequest) -> RenderResult:
        style = self.resolve_style(request.style)
        width, height = self.output_size(request)
        data = request.data or {}

        fig = create_figure(width, height, self._bg_color(style))
        canvas = add_canvas(fig)

        self._draw_title(canvas, request)
        self._draw_subtitle(canvas, request)

        renderer = {
            "glass_3d": self._render_glass_3d,
            "neon_tubes": self._render_neon_tubes,
            "gradient_sky": self._render_gradient_sky,
            "crystal_pillars": self._render_crystal_pillars,
        }[style]

        renderer(fig, canvas, data, width, height)

        add_reference_footer(
            canvas,
            "Neo Legend Luxury Bar Chart | Professional Data Visualization Artwork",
            color=self._footer_color(style),
        )
        return self.result(save_png(fig), style)

    def _bg_color(self, style: str) -> str:
        return {
            "glass_3d": "#1a1a2e",
            "neon_tubes": "#0a0a0a",
            "gradient_sky": "#2c3e50",
            "crystal_pillars": "#0d1b2a",
        }[style]

    def _footer_color(self, style: str) -> str:
        if style == "neon_tubes":
            return "#444444"
        if style == "crystal_pillars":
            return "#4a6fa5"
        return "#8f8f8f"

    def _draw_title(self, canvas: plt.Axes, request: RenderRequest) -> None:
        title_text = (request.title or "Performance Analytics").title()
        title_config = {
            "glass_3d": {"color": "#f0f0f0", "fontsize": 48, "fontweight": "black"},
            "neon_tubes": {"color": "#ffffff", "fontsize": 50, "fontweight": "black"},
            "gradient_sky": {"color": "#ffffff", "fontsize": 48, "fontweight": "black"},
            "crystal_pillars": {"color": "#e0e0e0", "fontsize": 48, "fontweight": "black"},
        }
        cfg = title_config.get(self.resolve_style(request.style), title_config["glass_3d"])
        canvas.text(0.5, 0.94, title_text, ha="center", va="center", **cfg)

    def _draw_subtitle(self, canvas: plt.Axes, request: RenderRequest) -> None:
        sub_text = request.subtitle or "Luxury Data Visualization | Generated by Neo Legend"
        sub_config = {
            "glass_3d": {"color": "#a0a0b8", "fontsize": 15},
            "neon_tubes": {"color": "#666666", "fontsize": 14},
            "gradient_sky": {"color": "#d0e0f0", "fontsize": 15},
            "crystal_pillars": {"color": "#8899aa", "fontsize": 15},
        }
        cfg = sub_config.get(self.resolve_style(request.style), sub_config["glass_3d"])
        canvas.text(0.5, 0.898, sub_text, ha="center", va="center", **cfg)

    def _extract_data(self, data: dict[str, Any]) -> tuple[list[str], list[float], list[str] | None, list[dict] | None]:
        labels = data.get("labels", ["Category A", "B", "C", "D", "E"])
        values = data.get("values", [85, 72, 90, 68, 75])
        colors = data.get("colors")
        grouped = data.get("grouped")
        return labels, values, colors, grouped

    def _resolve_colors(self, colors: list[str] | None, n: int, palette: list[str]) -> list[str]:
        if colors and len(colors) >= n:
            return colors[:n]
        return [palette[i % len(palette)] for i in range(n)]

    def _darken_color(self, hex_color: str, factor: float) -> str:
        hex_color = hex_color.lstrip("#")
        r = int(hex_color[0:2], 16)
        g = int(hex_color[2:4], 16)
        b = int(hex_color[4:6], 16)
        r = int(r * factor)
        g = int(g * factor)
        b = int(b * factor)
        return f"#{r:02x}{g:02x}{b:02x}"

    def _lighten_color(self, hex_color: str, factor: float) -> str:
        hex_color = hex_color.lstrip("#")
        r = int(hex_color[0:2], 16)
        g = int(hex_color[2:4], 16)
        b = int(hex_color[4:6], 16)
        r = min(255, int(r + (255 - r) * factor))
        g = min(255, int(g + (255 - g) * factor))
        b = min(255, int(b + (255 - b) * factor))
        return f"#{r:02x}{g:02x}{b:02x}"

    # ──────────────────── Style 1: Glass 3D ────────────────────

    def _render_glass_3d(
        self, fig: plt.Figure, canvas: plt.Axes, data: dict[str, Any], width: int, height: int
    ) -> None:
        labels, values, colors, grouped = self._extract_data(data)
        ax = fig.add_axes([0.10, 0.12, 0.82, 0.70], facecolor="#1a1a2e")

        if grouped:
            self._draw_grouped_glass(ax, grouped, labels)
        else:
            bar_colors = self._resolve_colors(colors, len(values), self._DEFAULT_PALETTE)
            self._draw_single_glass_bars(ax, labels, values, bar_colors)

        ax.set_facecolor("#1a1a2e")
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.tick_params(axis="both", colors="#888899", labelsize=11)
        ax.xaxis.label.set_color("#aaaabb")
        ax.yaxis.label.set_color("#aaaabb")
        ax.set_xlabel("Categories", fontsize=13, fontweight="bold", labelpad=10)
        ax.set_ylabel("Values", fontsize=13, fontweight="bold", labelpad=10)
        ax.grid(axis="y", linestyle="--", alpha=0.15, color="#666688")

    def _draw_single_glass_bars(
        self, ax: plt.Axes, labels: list[str], values: list[float], colors: list[str]
    ) -> None:
        n = len(labels)
        x_pos = np.arange(n)
        bar_width = 0.60
        max_val = max(values) * 1.2

        shadow_img = None
        for i, (x, val, col) in enumerate(zip(x_pos, values, colors)):
            bar_h = val / max_val * 0.85
            bw = bar_width * 0.75
            x_c = x - bw / 2
            y_c = 0.03

            dark_col = self._darken_color(col, 0.30)
            shadow = FancyBboxPatch(
                (x_c + 0.04, y_c - 0.04),
                bw,
                bar_h,
                boxstyle="round,pad=0.02,rounding_size=0.02",
                facecolor=dark_col,
                edgecolor="none",
                alpha=0.30,
                zorder=1,
            )
            ax.add_patch(shadow)

            cmap = make_gradient([col, self._lighten_color(col, 0.55)], f"glass_{i}")
            for seg in range(24):
                seg_y = y_c + seg / 24 * bar_h
                seg_h = bar_h / 24 + 0.001
                ratio = seg / 23
                seg_alpha = 0.90 - ratio * 0.50
                seg_col = cmap(ratio)
                seg_patch = FancyBboxPatch(
                    (x_c, seg_y),
                    bw,
                    seg_h,
                    boxstyle="round,pad=0.01,rounding_size=0.01" if seg == 0 else "square",
                    facecolor=seg_col,
                    edgecolor="none",
                    alpha=seg_alpha,
                    zorder=3,
                )
                ax.add_patch(seg_patch)

            highlight = FancyBboxPatch(
                (x_c + 0.01, y_c),
                0.025,
                bar_h,
                boxstyle="round,pad=0.005,rounding_size=0.005",
                facecolor="#ffffff",
                edgecolor="none",
                alpha=0.55,
                zorder=4,
            )
            ax.add_patch(highlight)

            top_ell = Ellipse(
                (x_c + bw / 2, y_c + bar_h),
                width=bw * 0.95,
                height=0.028,
                facecolor=self._lighten_color(col, 0.35),
                edgecolor="none",
                alpha=0.80,
                zorder=5,
            )
            ax.add_patch(top_ell)

            ax.text(
                x_c + bw / 2,
                y_c + bar_h + 0.035,
                f"{val}",
                ha="center",
                va="bottom",
                fontsize=12,
                fontweight="bold",
                color="#e8e8f0",
                zorder=10,
            )

        ax.set_xticks(x_pos)
        ax.set_xticklabels(labels, fontsize=11, color="#bbbccd")
        ax.set_xlim(-0.6, n - 0.4)
        ax.set_ylim(0, 1.0)

    def _draw_grouped_glass(self, ax: plt.Axes, grouped: list[dict], labels: list[str]) -> None:
        n_groups = len(labels)
        n_series = len(grouped)
        group_width = 0.72
        bar_w = group_width / n_series * 0.82
        max_val = max(g["values"][i] for g in grouped for i in range(len(g["values"]))) * 1.2

        for gi, group in enumerate(grouped):
            gcolor = group.get("color", self._DEFAULT_PALETTE[gi % len(self._DEFAULT_PALETTE)])
            gvalues = group["values"]
            for bi, (val, lbl) in enumerate(zip(gvalues, labels)):
                x_center = bi + (gi - n_series / 2 + 0.5) * (group_width / n_series)
                bw = bar_w
                x_c = x_center - bw / 2
                bar_h = val / max_val * 0.82
                y_c = 0.02

                dark_col = self._darken_color(gcolor, 0.30)
                shadow = FancyBboxPatch(
                    (x_c + 0.03, y_c - 0.03),
                    bw,
                    bar_h,
                    boxstyle="round,pad=0.015,rounding_size=0.015",
                    facecolor=dark_col,
                    edgecolor="none",
                    alpha=0.28,
                    zorder=1,
                )
                ax.add_patch(shadow)

                cmap = make_gradient([gcolor, self._lighten_color(gcolor, 0.50)], f"g_glass_{gi}_{bi}")
                for seg in range(18):
                    seg_y = y_c + seg / 18 * bar_h
                    seg_h = bar_h / 18 + 0.001
                    ratio = seg / 17
                    sp = FancyBboxPatch(
                        (x_c, seg_y),
                        bw,
                        seg_h,
                        facecolor=cmap(ratio),
                        edgecolor="none",
                        alpha=0.85 - ratio * 0.45,
                        zorder=3,
                    )
                    ax.add_patch(sp)

                hl = FancyBboxPatch(
                    (x_c + 0.008, y_c),
                    0.018,
                    bar_h,
                    facecolor="#ffffff",
                    edgecolor="none",
                    alpha=0.45,
                    zorder=4,
                )
                ax.add_patch(hl)

                top_e = Ellipse(
                    (x_c + bw / 2, y_c + bar_h),
                    width=bw * 0.92,
                    height=0.022,
                    facecolor=self._lighten_color(gcolor, 0.32),
                    edgecolor="none",
                    alpha=0.75,
                    zorder=5,
                )
                ax.add_patch(top_e)

        handles = [
            mpatches.Patch(color=g.get("color", self._DEFAULT_PALETTE[i % len(self._DEFAULT_PALETTE)]), label=g["label"])
            for i, g in enumerate(grouped)
        ]
        ax.legend(handles=handles, loc="upper right", framealpha=0.2, labelcolor="#ccccee", fontsize=11)
        ax.set_xticks(range(n_groups))
        ax.set_xticklabels(labels, fontsize=11, color="#bbbccd")
        ax.set_xlim(-0.6, n_groups - 0.4)
        ax.set_ylim(0, 1.0)

    # ──────────────────── Style 2: Neon Tubes ────────────────────

    def _render_neon_tubes(
        self, fig: plt.Figure, canvas: plt.Axes, data: dict[str, Any], width: int, height: int
    ) -> None:
        labels, values, colors, grouped = self._extract_data(data)
        ax = fig.add_axes([0.10, 0.12, 0.82, 0.70], facecolor="#0a0a0a")

        self._draw_neon_ambient_glow(canvas)

        if grouped:
            self._draw_grouped_neon(ax, grouped, labels)
        else:
            bar_colors = self._resolve_colors(colors, len(values), self._NEON_PALETTE)
            self._draw_neon_bars(ax, labels, values, bar_colors)

        ax.set_facecolor("#0a0a0a")
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.tick_params(axis="both", colors="#555555", labelsize=11)
        ax.set_xlabel("Categories", fontsize=13, fontweight="bold", color="#777777", labelpad=10)
        ax.set_ylabel("Values", fontsize=13, fontweight="bold", color="#777777", labelpad=10)
        ax.grid(axis="y", linestyle="--", alpha=0.08, color="#444444")

    def _draw_neon_ambient_glow(self, canvas: plt.Axes) -> None:
        n_rings = 40
        for i in range(n_rings, 0, -1):
            r = i / n_rings * 0.7
            alpha = 0.012 * (1 - i / n_rings)
            ell = Ellipse((0.5, 0.50), r * 1.6, r * 1.1, facecolor="#333366", edgecolor="none", alpha=alpha, zorder=0)
            canvas.add_patch(ell)

    def _draw_neon_bars(
        self, ax: plt.Axes, labels: list[str], values: list[float], colors: list[str]
    ) -> None:
        n = len(labels)
        x_pos = np.arange(n)
        max_val = max(values) * 1.2

        for i, (x, val, col) in enumerate(zip(x_pos, values, colors)):
            bar_h = val / max_val * 0.85
            bw = 0.55

            for lw, alpha in [(7, 0.06), (4.5, 0.14), (2.8, 0.35), (1.3, 0.88)]:
                ax.bar(
                    x,
                    bar_h,
                    width=bw,
                    edgecolor=col,
                    linewidth=lw,
                    facecolor=col,
                    alpha=alpha,
                    zorder=3 if lw < 3 else 2,
                )

            ax.bar(x, bar_h, width=bw * 0.92, facecolor=col, alpha=0.07, edgecolor="none", zorder=1)

            ax.text(
                x,
                bar_h + 0.038,
                f"{val}",
                ha="center",
                va="bottom",
                fontsize=13,
                fontweight="bold",
                color=col,
                alpha=0.92,
                zorder=10,
            )

        ax.set_xticks(x_pos)
        ax.set_xticklabels(labels, fontsize=11, color="#666666")
        ax.set_xlim(-0.6, n - 0.4)
        ax.set_ylim(0, 1.0)

    def _draw_grouped_neon(self, ax: plt.Axes, grouped: list[dict], labels: list[str]) -> None:
        n_groups = len(labels)
        n_series = len(grouped)
        group_width = 0.70
        bar_w = group_width / n_series * 0.78
        max_val = max(g["values"][i] for g in grouped for i in range(len(g["values"]))) * 1.2

        for gi, group in enumerate(grouped):
            gcolor = group.get("color", self._NEON_PALETTE[gi % len(self._NEON_PALETTE)])
            gvalues = group["values"]
            for bi, (val, lbl) in enumerate(zip(gvalues, labels)):
                x_center = bi + (gi - n_series / 2 + 0.5) * (group_width / n_series)
                bar_h = val / max_val * 0.82

                for lw, alpha in [(6, 0.05), (3.8, 0.13), (2.2, 0.33), (1.1, 0.85)]:
                    ax.bar(
                        x_center,
                        bar_h,
                        width=bar_w,
                        edgecolor=gcolor,
                        linewidth=lw,
                        facecolor=gcolor,
                        alpha=alpha,
                        zorder=3 if lw < 3 else 2,
                    )

                ax.bar(x_center, bar_h, width=bar_w * 0.90, facecolor=gcolor, alpha=0.06, edgecolor="none", zorder=1)

        handles = [
            mpatches.Patch(color=g.get("color", self._NEON_PALETTE[i % len(self._NEON_PALETTE)]), label=g["label"])
            for i, g in enumerate(grouped)
        ]
        ax.legend(handles=handles, loc="upper right", framealpha=0.12, labelcolor="#aaaaaa", fontsize=11)
        ax.set_xticks(range(n_groups))
        ax.set_xticklabels(labels, fontsize=11, color="#666666")
        ax.set_xlim(-0.6, n_groups - 0.4)
        ax.set_ylim(0, 1.0)

    # ──────────────────── Style 3: Gradient Sky ────────────────────

    def _render_gradient_sky(
        self, fig: plt.Figure, canvas: plt.Axes, data: dict[str, Any], width: int, height: int
    ) -> None:
        labels, values, colors, grouped = self._extract_data(data)
        self._draw_sky_background(canvas)

        ax = fig.add_axes([0.10, 0.12, 0.82, 0.70])
        ax.set_facecolor("none")

        if grouped:
            self._draw_grouped_sky(ax, grouped, labels)
        else:
            bar_colors = self._resolve_colors(colors, len(values), self._DEFAULT_PALETTE)
            self._draw_sky_bars(ax, labels, values, bar_colors)

        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.tick_params(axis="both", colors="#555566", labelsize=11)
        ax.set_xlabel("Categories", fontsize=13, fontweight="bold", color="#445566", labelpad=10)
        ax.set_ylabel("Values", fontsize=13, fontweight="bold", color="#445566", labelpad=10)
        ax.grid(axis="y", linestyle="--", alpha=0.12, color="#8899aa")

        self._draw_cloud_decorations(canvas)

    def _draw_sky_background(self, canvas: plt.Axes) -> None:
        sky_grad = np.linspace(0, 1, 256).reshape(-1, 1)
        sky_colors = ["#2c3e50", "#3498db", "#5dade2", "#85c1e9", "#aed6f1", "#d4e6f1", "#ecf0f1"]
        cmap = make_gradient(sky_colors, "sky_bg")
        canvas.imshow(sky_grad.T, aspect="auto", extent=[0, 1, 0, 1], cmap=cmap, zorder=0)

    def _draw_cloud_decorations(self, canvas: plt.Axes) -> None:
        cloud_positions = [(0.12, 0.76), (0.78, 0.79), (0.35, 0.81), (0.62, 0.77)]
        for cx, cy in cloud_positions:
            cloud = Ellipse((cx, cy), 0.12, 0.04, facecolor="#ffffff", edgecolor="none", alpha=0.10, zorder=0)
            canvas.add_patch(cloud)
            c2 = Ellipse((cx + 0.04, cy + 0.008), 0.08, 0.032, facecolor="#ffffff", edgecolor="none", alpha=0.08, zorder=0)
            canvas.add_patch(c2)

    def _draw_sky_bars(
        self, ax: plt.Axes, labels: list[str], values: list[float], colors: list[str]
    ) -> None:
        n = len(labels)
        x_pos = np.arange(n)
        max_val = max(values) * 1.2
        sunset = self._SUNSET_PALETTES

        for i, (x, val) in enumerate(zip(x_pos, values)):
            pair = sunset[i % len(sunset)]
            cmap = make_gradient(pair, f"sunset_{i}")
            bar_h = val / max_val * 0.85
            bw = 0.58
            x_c = x - bw / 2
            y_c = 0.02

            n_seg = 28
            for seg in range(n_seg):
                seg_y = y_c + seg / n_seg * bar_h
                seg_h = bar_h / n_seg + 0.001
                ratio = seg / (n_seg - 1)
                sp = FancyBboxPatch(
                    (x_c, seg_y),
                    bw,
                    seg_h,
                    boxstyle="round,pad=0.03,rounding_size=0.03" if seg == 0 else "square",
                    facecolor=cmap(ratio),
                    edgecolor="none",
                    alpha=0.92,
                    zorder=3,
                )
                ax.add_patch(sp)

            ax.text(
                x_c + bw / 2,
                y_c + bar_h + 0.032,
                f"{val}",
                ha="center",
                va="bottom",
                fontsize=12,
                fontweight="bold",
                color=pair[0],
                zorder=10,
            )

        ax.set_xticks(x_pos)
        ax.set_xticklabels(labels, fontsize=11, color="#445566")
        ax.set_xlim(-0.6, n - 0.4)
        ax.set_ylim(0, 1.0)

    def _draw_grouped_sky(self, ax: plt.Axes, grouped: list[dict], labels: list[str]) -> None:
        n_groups = len(labels)
        n_series = len(grouped)
        group_width = 0.70
        bar_w = group_width / n_series * 0.80
        max_val = max(g["values"][i] for g in grouped for i in range(len(g["values"]))) * 1.2
        sunset = self._SUNSET_PALETTES

        for gi, group in enumerate(grouped):
            gcolor = group.get("color", self._DEFAULT_PALETTE[gi % len(self._DEFAULT_PALETTE)])
            pair = sunset[gi % len(sunset)]
            cmap = make_gradient(pair, f"g_sunset_{gi}")
            gvalues = group["values"]
            for bi, val in enumerate(gvalues):
                x_center = bi + (gi - n_series / 2 + 0.5) * (group_width / n_series)
                bar_h = val / max_val * 0.82
                x_c = x_center - bar_w / 2
                y_c = 0.018

                for seg in range(22):
                    seg_y = y_c + seg / 22 * bar_h
                    seg_h = bar_h / 22 + 0.001
                    ratio = seg / 21
                    sp = FancyBboxPatch(
                        (x_c, seg_y),
                        bar_w,
                        seg_h,
                        facecolor=cmap(ratio),
                        edgecolor="none",
                        alpha=0.90,
                        zorder=3,
                    )
                    ax.add_patch(sp)

        handles = [
            mpatches.Patch(color=sunset[i % len(sunset)][0], label=g["label"]) for i, g in enumerate(grouped)
        ]
        ax.legend(handles=handles, loc="upper right", framealpha=0.25, labelcolor="#445566", fontsize=11)
        ax.set_xticks(range(n_groups))
        ax.set_xticklabels(labels, fontsize=11, color="#445566")
        ax.set_xlim(-0.6, n_groups - 0.4)
        ax.set_ylim(0, 1.0)

    # ──────────────────── Style 4: Crystal Pillars ────────────────────

    def _render_crystal_pillars(
        self, fig: plt.Figure, canvas: plt.Axes, data: dict[str, Any], width: int, height: int
    ) -> None:
        labels, values, colors, grouped = self._extract_data(data)
        ax = fig.add_axes([0.10, 0.12, 0.82, 0.70], facecolor="#0d1b2a")

        if grouped:
            self._draw_grouped_crystal(ax, grouped, labels)
        else:
            bar_colors = self._resolve_colors(colors, len(values), self._DEFAULT_PALETTE)
            self._draw_crystal_bars(ax, labels, values, bar_colors)

        ax.set_facecolor("#0d1b2a")
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.tick_params(axis="both", colors="#7788aa", labelsize=11)
        ax.set_xlabel("Categories", fontsize=13, fontweight="bold", color="#8899bb", labelpad=10)
        ax.set_ylabel("Values", fontsize=13, fontweight="bold", color="#8899bb", labelpad=10)
        ax.grid(axis="y", linestyle="--", alpha=0.10, color="#445577")

    def _draw_crystal_bars(
        self, ax: plt.Axes, labels: list[str], values: list[float], colors: list[str]
    ) -> None:
        n = len(labels)
        x_pos = np.arange(n)
        max_val = max(values) * 1.2

        crystal_grad = ["#a8dadc", "#cce5e8", "#e8f0f2", "#f1faee"]

        for i, (x, val, col) in enumerate(zip(x_pos, values, colors)):
            bar_h = val / max_val * 0.84
            bw = 0.56
            x_c = x - bw / 2
            y_c = 0.025

            base = FancyBboxPatch(
                (x_c - 0.015, y_c - 0.018),
                bw + 0.03,
                0.025,
                boxstyle="round,pad=0.008,rounding_size=0.008",
                facecolor="#1b2838",
                edgecolor="none",
                alpha=0.85,
                zorder=1,
            )
            ax.add_patch(base)

            cmap = make_gradient(crystal_grad, f"crystal_{i}")
            main_bar = FancyBboxPatch(
                (x_c, y_c),
                bw,
                bar_h,
                boxstyle="round,pad=0.025,rounding_size=0.025",
                facecolor=cmap(0.5),
                edgecolor="none",
                alpha=0.92,
                zorder=3,
            )
            ax.add_patch(main_bar)

            n_seg = 20
            for seg in range(n_seg):
                seg_y = y_c + seg / n_seg * bar_h
                seg_h = bar_h / n_seg + 0.001
                ratio = seg / (n_seg - 1)
                sp = FancyBboxPatch(
                    (x_c, seg_y),
                    bw,
                    seg_h,
                    boxstyle="square",
                    facecolor=cmap(ratio),
                    edgecolor="none",
                    alpha=0.88,
                    zorder=3,
                )
                ax.add_patch(sp)

            step_px = 0.020
            for di in np.arange(0, bar_h, step_px):
                ly = y_c + di
                lx_start = x_c + 0.02
                lx_end = x_c + bw - 0.02
                ax.plot(
                    [lx_start, lx_end],
                    [ly + step_px * 0.4, ly + step_px * 1.2],
                    color="#ffffff",
                    linewidth=0.5,
                    alpha=0.13,
                    zorder=4,
                )

            gloss_h = bar_h * 0.28
            gloss = FancyBboxPatch(
                (x_c + 0.015, y_c + bar_h - gloss_h),
                bw * 0.28,
                gloss_h,
                boxstyle="round,pad=0.015,rounding_size=0.015",
                facecolor="#ffffff",
                edgecolor="none",
                alpha=0.14,
                zorder=5,
            )
            ax.add_patch(gloss)

            edge_highlight = FancyBboxPatch(
                (x_c, y_c),
                bw,
                bar_h,
                boxstyle="round,pad=0.025,rounding_size=0.025",
                facecolor="none",
                edgecolor="#ffffff",
                linewidth=1.0,
                alpha=0.45,
                zorder=6,
            )
            ax.add_patch(edge_highlight)

            ax.text(
                x_c + bw / 2,
                y_c + bar_h + 0.035,
                f"{val}",
                ha="center",
                va="bottom",
                fontsize=13,
                fontweight="bold",
                color="#ffd700",
                zorder=10,
            )

        ax.set_xticks(x_pos)
        ax.set_xticklabels(labels, fontsize=11, color="#8899bb")
        ax.set_xlim(-0.6, n - 0.4)
        ax.set_ylim(0, 1.0)

    def _draw_grouped_crystal(self, ax: plt.Axes, grouped: list[dict], labels: list[str]) -> None:
        n_groups = len(labels)
        n_series = len(grouped)
        group_width = 0.70
        bar_w = group_width / n_series * 0.78
        max_val = max(g["values"][i] for g in grouped for i in range(len(g["values"]))) * 1.2
        crystal_grad = ["#a8dadc", "#cce5e8", "#e8f0f2", "#f1faee"]

        for gi, group in enumerate(grouped):
            gcolor = group.get("color", self._DEFAULT_PALETTE[gi % len(self._DEFAULT_PALETTE)])
            cmap = make_gradient(crystal_grad, f"g_crystal_{gi}")
            gvalues = group["values"]
            for bi, val in enumerate(gvalues):
                x_center = bi + (gi - n_series / 2 + 0.5) * (group_width / n_series)
                bar_h = val / max_val * 0.80
                x_c = x_center - bar_w / 2
                y_c = 0.020

                base = FancyBboxPatch(
                    (x_c - 0.012, y_c - 0.015),
                    bar_w + 0.024,
                    0.022,
                    boxstyle="round,pad=0.006,rounding_size=0.006",
                    facecolor="#1b2838",
                    edgecolor="none",
                    alpha=0.82,
                    zorder=1,
                )
                ax.add_patch(base)

                for seg in range(16):
                    seg_y = y_c + seg / 16 * bar_h
                    seg_h = bar_h / 16 + 0.001
                    ratio = seg / 15
                    sp = FancyBboxPatch(
                        (x_c, seg_y),
                        bar_w,
                        seg_h,
                        facecolor=cmap(ratio),
                        edgecolor="none",
                        alpha=0.85,
                        zorder=3,
                    )
                    ax.add_patch(sp)

                eh = FancyBboxPatch(
                    (x_c, y_c),
                    bar_w,
                    bar_h,
                    boxstyle="round,pad=0.02,rounding_size=0.02",
                    facecolor="none",
                    edgecolor="#ffffff",
                    linewidth=0.85,
                    alpha=0.38,
                    zorder=5,
                )
                ax.add_patch(eh)

                ax.text(
                    x_center,
                    y_c + bar_h + 0.028,
                    f"{val}",
                    ha="center",
                    va="bottom",
                    fontsize=10,
                    fontweight="bold",
                    color="#ffd700",
                    alpha=0.92,
                    zorder=10,
                )

        handles = [
            mpatches.Patch(facecolor="#d0e8ec", edgecolor="#ffffff", linewidth=1, alpha=0.7, label=g["label"])
            for g in grouped
        ]
        ax.legend(handles=handles, loc="upper right", framealpha=0.15, labelcolor="#8899bb", fontsize=11)
        ax.set_xticks(range(n_groups))
        ax.set_xticklabels(labels, fontsize=11, color="#8899bb")
        ax.set_xlim(-0.6, n_groups - 0.4)
        ax.set_ylim(0, 1.0)
