"""Court shooting terrain renderer skill."""

from __future__ import annotations

import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection
from matplotlib.colors import Normalize
from matplotlib.patches import Circle
from matplotlib.tri import Triangulation
import numpy as np

from neo_legend.models import RenderRequest, RenderResult
from neo_legend._court import draw_half_court, sample_shots
from neo_legend._plotting import (
    add_canvas,
    add_reference_footer,
    create_figure,
    make_gradient,
    save_png,
    seeded_rng,
)
from neo_legend.base import BaseLegendSkill, StyleDefinition


class CourtShotSkill(BaseLegendSkill):
    legend_type = "court_shot"
    display_name = "Court Shooting Terrain"
    default_style = "terrain"
    default_size = (1179, 1454)
    style_definitions = (
        StyleDefinition(
            "terrain",
            "Dark half-court shooting terrain with glowing efficiency zones.",
            (
                "6f95be795cc16e2d3b0e0f6425e12353.jpg",
                "542b1ddcb7b0ed0c8748915c4ab50e0a.jpg",
            ),
        ),
        StyleDefinition(
            "points_location",
            "Dark teal total-points-by-location hex map.",
            ("0ece60f1e357e60d332c2983bac940dd.jpg",),
        ),
        StyleDefinition(
            "kobe_shots",
            "White shot chart with made, missed, and assisted basketball markers.",
            ("8f8f3a2852825db7c630dec71b0a0cb9.jpg",),
        ),
        StyleDefinition("hex", "Hex-bin shot profile with red, cream, blue zone colors."),
        StyleDefinition("zone", "Annotated zone shot map with light boundaries and point clusters."),
    )

    def render(self, request: RenderRequest) -> RenderResult:
        style = self.resolve_style(request.style)
        width, height = self.output_size(request)
        content = self._render_png(request, style, width, height)
        return self.result(content, style)

    def _render_png(self, request: RenderRequest, style: str, width: int, height: int) -> bytes:
        if style == "points_location":
            return self._render_points_location(request, width, height)
        if style == "kobe_shots":
            return self._render_kobe_shots(request, width, height)

        fig = create_figure(width, height, "#020303")
        canvas = add_canvas(fig)
        title = request.title or "SCOTTIE PIPPEN"
        subtitle = request.subtitle or "1997-98 SHOOTING TERRAIN"

        canvas.text(
            0.5,
            0.905,
            title.upper(),
            color="#f5f4ec",
            fontsize=52,
            fontweight="black",
            ha="center",
            va="center",
        )
        canvas.text(
            0.5,
            0.855,
            subtitle.upper(),
            color="#b7b1b1",
            fontsize=18,
            fontweight="bold",
            ha="center",
            va="center",
        )

        court_ax = fig.add_axes([0.06, 0.06, 0.88, 0.58], facecolor="#020303")
        draw_half_court(court_ax, line_color="#dedbd0", line_width=1.05, alpha=0.62)
        shot_count = int(request.data.get("shot_count", 620))
        seed = int(request.data.get("seed", 11))
        x, y, value = sample_shots(seed=seed, count=shot_count)

        if style == "terrain":
            self._draw_terrain_mesh(court_ax, x, y, value)
        elif style == "hex":
            cmap = make_gradient(["#4b7cbf", "#f1edd1", "#d51e38"], "shot_hex")
            sizes = np.interp(value, (value.min(), value.max()), (18, 96))
            court_ax.scatter(x, y, c=value, s=sizes, cmap=cmap, marker="h", alpha=0.82, lw=0)
            court_ax.scatter(x[::9], y[::9], s=9, color="#fff4c7", alpha=0.65)
        else:
            self._draw_zones(court_ax, x, y, value)

        if style != "zone":
            for label, px, py in [
                ("51%", -165, 98),
                ("60%", 38, 75),
                ("42%", 178, 260),
                ("31%", -205, 315),
                ("40%", 112, 212),
            ]:
                court_ax.text(px, py, label, color="#f5f4ec", fontsize=14, fontweight="bold")

        add_reference_footer(canvas, "BY @KIRKGOLDSBERRY | GENERATED BY NEO LEGEND")
        return save_png(fig)

    @staticmethod
    def _draw_terrain_mesh(ax: plt.Axes, x: np.ndarray, y: np.ndarray, value: np.ndarray) -> None:
        rng = seeded_rng(412)
        terrain_x = np.concatenate([x, x[: len(x) // 2] + rng.normal(0, 16, len(x) // 2)])
        terrain_y = np.concatenate([y, y[: len(x) // 2] + rng.normal(0, 14, len(x) // 2)])
        terrain_value = np.concatenate([value, value[: len(x) // 2] + rng.normal(0, 0.18, len(x) // 2)])
        active = (
            (np.hypot(terrain_x, terrain_y - 52.5) < 150)
            | ((np.abs(terrain_x) > 115) & (terrain_y < 345))
            | ((terrain_y > 165) & (terrain_y < 385) & (np.abs(terrain_x) < 220))
        )
        terrain_x = terrain_x[active]
        terrain_y = terrain_y[active]
        terrain_value = terrain_value[active]
        tri = Triangulation(terrain_x, terrain_y)
        triangles = tri.triangles
        centers_x = terrain_x[triangles].mean(axis=1)
        centers_y = terrain_y[triangles].mean(axis=1)
        edge_lengths = np.ptp(terrain_x[triangles], axis=1) + np.ptp(terrain_y[triangles], axis=1)
        keep = (
            (edge_lengths < 58)
            & (
                (np.hypot(centers_x, centers_y - 52.5) < 165)
                | ((np.abs(centers_x) > 105) & (centers_y < 355))
                | ((centers_y > 155) & (centers_y < 395) & (np.abs(centers_x) < 225))
            )
        )
        polygons = [np.column_stack([terrain_x[indexes], terrain_y[indexes]]) for indexes in triangles[keep]]
        kept_x = centers_x[keep]
        kept_y = centers_y[keep]
        heat = (
            0.95 * np.exp(-(((kept_x + 165) / 82) ** 2 + ((kept_y - 235) / 95) ** 2))
            + 1.15 * np.exp(-(((kept_x - 10) / 82) ** 2 + ((kept_y - 65) / 72) ** 2))
            + 0.65 * np.exp(-(((kept_x - 150) / 72) ** 2 + ((kept_y - 225) / 92) ** 2))
            + 0.12 * rng.random(len(kept_x))
        )
        normalized = np.clip(heat / max(heat.max(), 1e-6), 0, 1)
        cmap = make_gradient(["#202123", "#2a292b", "#443037", "#913043", "#ef8e91"], "terrain_mesh")
        colors = [cmap(float(item)) for item in normalized]
        collection = PolyCollection(
            polygons,
            facecolors=colors,
            edgecolors="#47494d",
            linewidths=0.42,
            alpha=0.74,
        )
        ax.add_collection(collection)

        glow = np.clip(normalized - 0.28, 0, 1)
        ax.scatter(
            kept_x,
            kept_y,
            s=16 + glow * 96,
            c=glow,
            cmap=make_gradient(["#32252a", "#c23147", "#ffd0ca"], "terrain_glow"),
            alpha=0.20,
            lw=0,
        )

    @staticmethod
    def _draw_zones(ax: plt.Axes, x: np.ndarray, y: np.ndarray, value: np.ndarray) -> None:
        rim = np.hypot(x, y - 52.5) < 95
        left = (x < -115) & (y < 315)
        right = (x > 115) & (y < 315)
        arc = (y >= 165) & (np.abs(x) <= 210)

        colors = np.full(len(x), "#3a3d42", dtype=object)
        colors[arc] = "#5b303a"
        colors[left] = "#bd2441"
        colors[right] = "#66a9d1"
        colors[rim] = "#f0b1aa"
        sizes = np.interp(value, (value.min(), value.max()), (18, 72))

        ax.scatter(
            x,
            y,
            s=sizes,
            c=colors,
            marker="h",
            alpha=0.78,
            edgecolors="#27292c",
            linewidths=0.35,
        )
        ax.scatter(x[::8], y[::8], s=7, color="#f8d1cc", alpha=0.22)

        line_color = "#e5ddd1"
        for x_coord in [-220, 220]:
            ax.plot([x_coord, x_coord], [0, 140], color=line_color, lw=1.0, alpha=0.38)
        ax.plot([-220, -82], [140, 188], color=line_color, lw=0.9, alpha=0.38)
        ax.plot([220, 82], [140, 188], color=line_color, lw=0.9, alpha=0.38)
        ax.plot([-80, -80], [0, 190], color=line_color, lw=0.9, alpha=0.42)
        ax.plot([80, 80], [0, 190], color=line_color, lw=0.9, alpha=0.42)

        labels = [
            ("LEFT\n51%", -170, 118, "#d94156"),
            ("RIM\n60%", 0, 78, "#f3b9b1"),
            ("RIGHT\n42%", 170, 118, "#85c8e5"),
            ("ARC\n40%", 0, 255, "#b55f6c"),
            ("CORNER\n31%", -208, 48, "#b1d6e8"),
        ]
        for label, px, py, color in labels:
            ax.text(
                px,
                py,
                label,
                color="#f8f4ed",
                fontsize=12,
                fontweight="bold",
                ha="center",
                va="center",
                bbox={
                    "boxstyle": "round,pad=0.28",
                    "facecolor": color,
                    "edgecolor": "none",
                    "alpha": 0.55,
                },
            )

    def _render_points_location(self, request: RenderRequest, width: int, height: int) -> bytes:
        fig = create_figure(width, height, "#111b27")
        canvas = add_canvas(fig)
        self._draw_texture(canvas, "#243242", alpha=0.12)
        canvas.text(
            0.5,
            0.92,
            request.title or "Total Points By Location",
            color="#f4fbff",
            fontsize=54,
            fontweight="black",
            ha="center",
        )
        canvas.text(
            0.5,
            0.875,
            request.subtitle or "2020-21 Season | By @KirkGoldsberry",
            color="#f4fbff",
            fontsize=22,
            ha="center",
        )

        ax = fig.add_axes([0.03, 0.13, 0.94, 0.66], facecolor="none")
        draw_half_court(ax, line_color="#f1f8ff", line_width=1.65, alpha=0.92)
        points_x, points_y, values = self._points_location_data(request.data)
        hex_map = ax.hexbin(
            points_x,
            points_y,
            C=values,
            reduce_C_function=np.sum,
            gridsize=33,
            extent=(-250, 250, 0, 470),
            mincnt=1,
            cmap=make_gradient(
                ["#06343e", "#0a6b68", "#12a99b", "#35e5d7", "#d7fff8"],
                "total_points_teal",
            ),
            norm=Normalize(vmin=0, vmax=float(request.data.get("max_points", 800))),
            linewidths=0.18,
            edgecolors="#0e5960",
            alpha=0.96,
        )
        totals = hex_map.get_array()
        if np.ma.isMaskedArray(totals):
            totals = totals.compressed()
        else:
            totals = np.asarray(totals)
        if totals.size > 0:
            dynamic_max = max(float(np.percentile(totals, 96)), 800.0)
            hex_map.set_clim(0, dynamic_max)
        ax.scatter(points_x[::8], points_y[::8], s=10, color="#8ffcf2", alpha=0.10, lw=0)

        canvas.text(0.50, 0.095, "Total points scored on FGM", color="#f5fbff", fontsize=22, ha="center")
        labels = ["Less\nThan\n200", "200-\n400", "400-\n600", "600-\n800", "More\nThan\n800"]
        legend_colors = ["#06343e", "#0a6b68", "#12a99b", "#35e5d7", "#d7fff8"]
        for index, (label, color) in enumerate(zip(labels, legend_colors, strict=True)):
            x0 = 0.39 + index * 0.055
            canvas.scatter([x0], [0.052], marker="h", s=1600, color=color, edgecolor="#2bd4c3")
            text_color = "#0d2530" if index == len(labels) - 1 else "#f6ffff"
            canvas.text(
                x0,
                0.052,
                label,
                color=text_color,
                fontsize=10,
                fontweight="bold",
                ha="center",
                va="center",
            )
        canvas.text(
            0.085,
            0.07,
            "BASKETBALL\nUNIVERSE",
            color="#ffffff",
            fontsize=10,
            fontweight="black",
            ha="center",
            va="center",
            bbox={"boxstyle": "circle,pad=0.55", "facecolor": "#050609", "edgecolor": "#111111"},
        )
        return save_png(fig)

    def _render_kobe_shots(self, request: RenderRequest, width: int, height: int) -> bytes:
        fig = create_figure(width, height, "#ffffff")
        canvas = add_canvas(fig)
        canvas.text(
            0.5,
            0.93,
            request.title or "Kobe Bryant",
            color="#020202",
            fontsize=58,
            fontweight="black",
            ha="center",
        )
        canvas.text(
            0.5,
            0.875,
            request.subtitle or "January 22, 2006 | 81 Points Scored | 5 Points Assisted",
            color="#111111",
            fontsize=22,
            ha="center",
        )

        ax = fig.add_axes([0.03, 0.08, 0.94, 0.68], facecolor="#ffffff")
        draw_half_court(ax, line_color="#111111", line_width=1.25, alpha=0.98)
        made, missed, assisted = self._kobe_shot_data()
        self._draw_basketball_markers(ax, missed[:, 0], missed[:, 1], "#ffffff", 230)
        self._draw_basketball_markers(ax, made[:, 0], made[:, 1], "#e57f48", 230)
        self._draw_basketball_markers(ax, assisted[:, 0], assisted[:, 1], "#14b85d", 250)

        legend = [("Made Shots", "#e57f48"), ("Missed Shots", "#ffffff"), ("Assisted Shots", "#14b85d")]
        for index, (label, color) in enumerate(legend):
            y0 = 0.055 - index * 0.018
            canvas.scatter([0.045], [y0], marker="o", s=180, color=color, edgecolor="#111111", lw=0.7)
            canvas.text(0.067, y0, label, color="#111111", fontsize=17, ha="left", va="center")
        return save_png(fig)

    @staticmethod
    def _points_location_data(data: dict) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        raw_shots = data.get("shots")
        if isinstance(raw_shots, list) and raw_shots:
            x = np.array([float(shot["x"]) for shot in raw_shots], dtype=float)
            y = np.array([float(shot["y"]) for shot in raw_shots], dtype=float)
            values = np.array([float(shot.get("points", 2.0)) for shot in raw_shots], dtype=float)
            return np.clip(x, -238, 238), np.clip(y, 8, 438), np.maximum(values, 0)

        rng = seeded_rng(int(data.get("seed", 2021)))
        zones = data.get("scoring_zones")
        if not isinstance(zones, list) or not zones:
            zones = CourtShotSkill._default_points_location_zones()

        x_parts: list[np.ndarray] = []
        y_parts: list[np.ndarray] = []
        value_parts: list[np.ndarray] = []
        for zone in zones:
            if not isinstance(zone, dict):
                continue
            count = int(zone.get("count", 100))
            points_per_event = float(zone.get("points_per_event", 6.0))
            jitter = float(zone.get("point_jitter", 0.18))
            if zone.get("shape") == "arc":
                angle_min, angle_max = zone.get("angle_range", [24, 156])
                angles = rng.uniform(np.deg2rad(angle_min), np.deg2rad(angle_max), count)
                radius = rng.normal(float(zone.get("radius", 235)), float(zone.get("radius_sd", 12)), count)
                xs = radius * np.cos(angles)
                ys = 52.5 + radius * np.sin(angles)
            else:
                center_x, center_y = zone.get("center", [0, 52.5])
                spread_x, spread_y = zone.get("spread", [30, 30])
                xs = rng.normal(float(center_x), float(spread_x), count)
                ys = rng.normal(float(center_y), float(spread_y), count)

            x_parts.append(np.clip(xs, -238, 238))
            y_parts.append(np.clip(ys, 8, 438))
            value_parts.append(points_per_event * rng.uniform(1 - jitter, 1 + jitter, count))

        return np.concatenate(x_parts), np.concatenate(y_parts), np.concatenate(value_parts)

    @staticmethod
    def _default_points_location_zones() -> list[dict]:
        return [
            {
                "name": "rim",
                "center": [0, 58],
                "spread": [36, 28],
                "count": 900,
                "points_per_event": 8.8,
            },
            {
                "name": "paint",
                "center": [0, 142],
                "spread": [24, 56],
                "count": 430,
                "points_per_event": 6.2,
            },
            {
                "name": "above_break_three",
                "shape": "arc",
                "angle_range": [25, 155],
                "radius": 235,
                "radius_sd": 12,
                "count": 760,
                "points_per_event": 3.7,
            },
            {
                "name": "left_corner",
                "center": [-222, 96],
                "spread": [8, 42],
                "count": 170,
                "points_per_event": 3.2,
            },
            {
                "name": "right_corner",
                "center": [222, 96],
                "spread": [8, 42],
                "count": 170,
                "points_per_event": 3.2,
            },
            {
                "name": "short_midrange",
                "center": [0, 215],
                "spread": [52, 28],
                "count": 130,
                "points_per_event": 2.4,
            },
        ]

    @staticmethod
    def _kobe_shot_data() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        rng = seeded_rng(81)
        made_x, made_y, _ = sample_shots(seed=81, count=32)
        missed_x, missed_y, _ = sample_shots(seed=24, count=24)
        assisted = np.array([[-78, 78], [0, 382], [-60, 45]], dtype=float)
        made = np.column_stack([made_x, made_y])
        missed = np.column_stack([missed_x, missed_y])
        rim_cluster = np.column_stack([rng.normal(0, 32, 14), rng.normal(55, 26, 14)])
        made = np.vstack([made[:22], rim_cluster])
        return made, missed, assisted

    @staticmethod
    def _draw_basketball_markers(
        ax: plt.Axes,
        x: np.ndarray,
        y: np.ndarray,
        color: str,
        size: float,
    ) -> None:
        ax.scatter(x, y, s=size, color=color, edgecolor="#111111", linewidth=0.7, zorder=6)
        for xi, yi in zip(x, y, strict=True):
            ax.plot([xi - 8, xi + 8], [yi, yi], color="#111111", lw=0.45, alpha=0.75, zorder=7)
            ax.plot([xi, xi], [yi - 8, yi + 8], color="#111111", lw=0.45, alpha=0.75, zorder=7)
            ax.add_patch(Circle((xi, yi), 6.0, fill=False, edgecolor="#111111", lw=0.35, alpha=0.70, zorder=7))

    @staticmethod
    def _draw_texture(canvas: plt.Axes, color: str, alpha: float) -> None:
        rng = seeded_rng(44)
        x = rng.uniform(0, 1, 1800)
        y = rng.uniform(0, 1, 1800)
        canvas.scatter(x, y, s=rng.uniform(0.4, 2.2, 1800), color=color, alpha=alpha, lw=0)
