"""Luxury radar chart renderer skill with three stunning visual variants."""

from __future__ import annotations

import colorsys
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Ellipse, FancyBboxPatch, PathPatch
from matplotlib.path import Path

from neo_legend.models import RenderRequest, RenderResult
from neo_legend._plotting import (
    add_canvas,
    add_reference_footer,
    create_figure,
    make_gradient,
    save_png,
    seeded_rng,
)
from neo_legend.base import BaseLegendSkill, StyleDefinition


class RadarChartSkill(BaseLegendSkill):
    legend_type = "radar_chart"
    display_name = "Luxury Radar Chart"
    default_style = "neon_glow"
    default_size = (1200, 1400)
    style_definitions = (
        StyleDefinition("neon_glow", "Neon glow effect with deep dark background and luminous lines."),
        StyleDefinition(
            "crystal_metal",
            "Crystal metallic texture with silver gradients and reflective highlights.",
        ),
        StyleDefinition("gradient_rainbow", "Rainbow gradient with HSV color transitions and star markers."),
    )

    def render(self, request: RenderRequest) -> RenderResult:
        style = self.resolve_style(request.style)
        width, height = self.output_size(request)
        content = self._render_png(request, style, width, height)
        return self.result(content, style)

    def _render_png(self, request: RenderRequest, style: str, width: int, height: int) -> bytes:
        data = self._extract_data(request.data)
        categories = data["categories"]
        datasets = data["datasets"]

        bg_color = {
            "neon_glow": "#0a0a1a",
            "crystal_metal": "#1a1a2e",
            "gradient_rainbow": "#000000",
        }[style]

        fig = create_figure(width, height, bg_color)
        canvas = add_canvas(fig)

        title = request.title or "PLAYER RADAR PROFILE"
        subtitle = request.subtitle or "MULTIDIMENSIONAL ANALYSIS"

        canvas.text(
            0.5,
            0.92,
            title.upper(),
            color="#ffffff",
            fontsize=48,
            fontweight="black",
            ha="center",
            va="center",
            family="sans-serif",
        )
        canvas.text(
            0.5,
            0.87,
            subtitle.upper(),
            color="#b0b0b0",
            fontsize=16,
            fontweight="bold",
            ha="center",
            va="center",
            family="sans-serif",
        )

        radar_ax = fig.add_axes([0.12, 0.15, 0.76, 0.62], projection="polar", facecolor=bg_color)
        radar_ax.set_ylim(0, 100)
        radar_ax.set_yticklabels([])
        radar_ax.grid(False)

        n_cats = len(categories)
        angles = np.linspace(0, 2 * np.pi, n_cats, endpoint=False).tolist()
        angles += angles[:1]

        if style == "neon_glow":
            self._draw_neon_glow(radar_ax, categories, datasets, angles, n_cats)
        elif style == "crystal_metal":
            self._draw_crystal_metal(radar_ax, categories, datasets, angles, n_cats)
        else:
            self._draw_gradient_rainbow(radar_ax, categories, datasets, angles, n_cats)

        legend_x = 0.5
        legend_y = 0.11
        for idx, dataset in enumerate(datasets):
            color = dataset["color"]
            canvas.scatter(
                [legend_x - 0.08 + idx * 0.16],
                [legend_y],
                s=120,
                c=[color],
                edgecolors="#ffffff",
                linewidths=1.5,
                zorder=10,
            )
            canvas.text(
                legend_x - 0.02 + idx * 0.16,
                legend_y,
                dataset["label"].upper(),
                color=color,
                fontsize=13,
                fontweight="bold",
                ha="left",
                va="center",
                family="sans-serif",
            )

        add_reference_footer(canvas, "GENERATED BY NEO LEGEND")
        return save_png(fig)

    @staticmethod
    def _extract_data(data: dict[str, Any]) -> dict[str, Any]:
        if data.get("categories") and data.get("datasets"):
            return data

        rng = seeded_rng(42)
        categories = data.get("categories", ["Score", "Rebound", "Assist", "Steal", "Block"])
        n_cats = len(categories)
        base_colors = ["#ff6b6b", "#4ecdc4", "#ffe66d", "#95e1d3", "#f38181"]
        datasets = [
            {
                "label": f"Player {chr(65 + i)}",
                "values": [int(rng.integers(50, 98)) for _ in range(n_cats)],
                "color": base_colors[i % len(base_colors)],
            }
            for i in range(2)
        ]
        return {"categories": categories, "datasets": datasets}

    def _draw_neon_glow(
        self,
        ax: plt.Axes,
        categories: list[str],
        datasets: list[dict],
        angles: list[float],
        n_cats: int,
    ) -> None:
        ax.set_facecolor("#0a0a1a")

        grid_levels = 5
        for level in range(grid_levels, 0, -1):
            radius = level * 20
            values_grid = [radius] * (n_cats + 1)
            alpha_grid = 0.06 + (grid_levels - level) * 0.03
            lw_grid = 0.5 + (grid_levels - level) * 0.2
            ax.plot(angles, values_grid, color="#3a3a6a", linewidth=lw_grid, alpha=alpha_grid)

        for i, angle in enumerate(angles[:-1]):
            ax.plot([angle, angle], [0, 100], color="#2a2a5a", linewidth=0.8, alpha=0.25)

        neon_colors = ["#00ffff", "#ff00ff", "#ffff00", "#00ff88", "#ff6688"]
        for i, cat in enumerate(categories):
            angle_rad = angles[i]
            x_text = 1.18 * np.cos(angle_rad - np.pi / 2)
            y_text = 1.18 * np.sin(angle_rad - np.pi / 2)
            color = neon_colors[i % len(neon_colors)]
            ax.text(
                angle_rad,
                108,
                cat.upper(),
                color=color,
                fontsize=13,
                fontweight="bold",
                ha="center",
                va="center",
                family="sans-serif",
            )
            ax.text(
                angle_rad,
                108,
                cat.upper(),
                color=color,
                fontsize=13,
                fontweight="bold",
                ha="center",
                va="center",
                family="sans-serif",
                alpha=0.4,
                zorder=1,
            )

        for dataset in datasets:
            values = dataset["values"] + dataset["values"][:1]
            color = dataset["color"]

            for lw, alpha in [(4, 0.15), (2.5, 0.4), (1, 0.9)]:
                ax.plot(angles, values, color=color, linewidth=lw, alpha=alpha, solid_capstyle="round")

            fill_alphas = [0.25, 0.12, 0.06]
            for fill_alpha in fill_alphas:
                ax.fill(angles, values, color=color, alpha=fill_alpha)

            for j, (angle, value) in enumerate(zip(angles[:-1], dataset["values"])):
                for size, a in [(25, 0.3), (16, 0.6), (9, 1.0)]:
                    ax.scatter(
                        [angle],
                        [value],
                        s=size,
                        c=[color],
                        edgecolors=["#ffffff"],
                        linewidths=1.2 if size == 9 else 0,
                        alpha=a,
                        zorder=10,
                    )

    def _draw_crystal_metal(
        self,
        ax: plt.Axes,
        categories: list[str],
        datasets: list[dict],
        angles: list[float],
        n_cats: int,
    ) -> None:
        ax.set_facecolor("#1a1a2e")

        grid_levels = 5
        for level in range(grid_levels, 0, -1):
            radius = level * 20
            values_grid = [radius] * (n_cats + 1)
            intensity = 0.15 + (grid_levels - level) * 0.08
            gray = int(80 + (grid_levels - level) * 20)
            grid_color = f"#{gray:02x}{gray:02x}{gray:02x}"
            ax.plot(angles, values_grid, color=grid_color, linewidth=1.0, alpha=intensity)

        for i, angle in enumerate(angles[:-1]):
            ax.plot([angle, angle], [0, 100], color="#555577", linewidth=0.8, alpha=0.3)

        for i, cat in enumerate(categories):
            angle_rad = angles[i]
            ax.text(
                angle_rad,
                108,
                cat.upper(),
                color="#e0e0e0",
                fontsize=13,
                fontweight="bold",
                ha="center",
                va="center",
                family="serif",
            )

        metal_gradients = {
            "default": make_gradient(["#c0c0c0", "#ffffff", "#e8e8e8"], "silver"),
            "gold": make_gradient(["#d4af37", "#ffd700", "#daa520"], "gold"),
            "bronze": make_gradient(["#cd7f32", "#ffaa33", "#b87333"], "bronze"),
        }

        for d_idx, dataset in enumerate(datasets):
            values = dataset["values"] + dataset["values"][:1]
            color = dataset["color"]

            gradient_name = ["default", "gold", "bronze"][d_idx % 3]
            cmap = metal_gradients[gradient_name]

            n_points = len(values)
            for j in range(n_points - 1):
                seg_values = values[j : j + 2]
                seg_angles = angles[j : j + 2]
                segment_color = cmap(j / max(n_points - 2, 1))
                ax.fill(seg_angles, seg_values, color=segment_color, alpha=0.7)
                ax.plot(seg_angles, seg_values, color="#d4af37", linewidth=2, solid_capstyle="round")

            max_value_idx = dataset["values"].index(max(dataset["values"]))
            peak_angle = angles[max_value_idx]
            peak_value = dataset["values"][max_value_idx]

            highlight = Ellipse(
                xy=(peak_angle, peak_value),
                width=0.15,
                height=6,
                angle=0,
                facecolor="#ffffff",
                edgecolor="none",
                alpha=0.6,
                zorder=15,
            )
            ax.add_patch(highlight)

            arc_angles = np.linspace(peak_angle - 0.12, peak_angle + 0.12, 30)
            arc_radii = peak_value + 3 * np.cos(np.linspace(0, np.pi, 30)) - 1
            ax.plot(arc_angles, arc_radii, color="#ffffff", linewidth=2, alpha=0.7, zorder=14)

            for j, (angle, value) in enumerate(zip(angles[:-1], dataset["values"])):
                diamond_size = 100 + (value / 100) * 60
                ax.scatter(
                    [angle],
                    [value],
                    s=diamond_size,
                    marker="D",
                    c=[color],
                    edgecolors=["#ffffff"],
                    linewidths=1.5,
                    alpha=0.95,
                    zorder=12,
                )
                inner_gray = int(200 + (value / 100) * 55)
                ax.scatter(
                    [angle],
                    [value],
                    s=diamond_size * 0.35,
                    marker="D",
                    c=[f"#{inner_gray:02x}{inner_gray:02x}{inner_gray:02x}"],
                    edgecolors="none",
                    alpha=0.8,
                    zorder=13,
                )

    def _draw_gradient_rainbow(
        self,
        ax: plt.Axes,
        categories: list[str],
        datasets: list[dict],
        angles: list[float],
        n_cats: int,
    ) -> None:
        ax.set_facecolor("#000000")

        grid_levels = 5
        rainbow_spectrum = [colorsys.hsv_to_rgb(i / grid_levels, 0.3, 0.4) for i in range(grid_levels)]
        for level in range(grid_levels, 0, -1):
            radius = level * 20
            values_grid = [radius] * (n_cats + 1)
            rgb = rainbow_spectrum[grid_levels - level]
            grid_color = f"#{int(rgb[0]*255):02x}{int(rgb[1]*255):02x}{int(rgb[2]*255):02x}"
            ax.plot(angles, values_grid, color=grid_color, linewidth=0.8, alpha=0.2)

        for i, angle in enumerate(angles[:-1]):
            hue = i / n_cats
            rgb = colorsys.hsv_to_rgb(hue, 0.8, 0.9)
            line_color = f"#{int(rgb[0]*255):02x}{int(rgb[1]*255):02x}{int(rgb[2]*255):02x}"
            ax.plot([angle, angle], [0, 100], color=line_color, linewidth=0.6, alpha=0.25)

        for i, cat in enumerate(categories):
            angle_rad = angles[i]
            hue = i / n_cats
            rgb = colorsys.hsv_to_rgb(hue, 1.0, 1.0)
            label_color = f"#{int(rgb[0]*255):02x}{int(rgb[1]*255):02x}{int(rgb[2]*255):02x}"
            ax.text(
                angle_rad,
                108,
                cat.upper(),
                color=label_color,
                fontsize=13,
                fontweight="bold",
                ha="center",
                va="center",
                family="sans-serif",
            )

        n_datasets = len(datasets)
        for d_idx, dataset in enumerate(datasets):
            values = dataset["values"] + dataset["values"][:1]
            base_hue = d_idx / max(n_datasets, 1)

            rainbow_colors = []
            for j in range(len(dataset["values"]) + 1):
                hue_offset = (j / n_cats + base_hue) % 1.0
                rgb = colorsys.hsv_to_rgb(hue_offset, 0.85, 0.95)
                hex_color = f"#{int(rgb[0]*255):02x}{int(rgb[1]*255):02x}{int(rgb[2]*255):02x}"
                rainbow_colors.append(hex_color)

            for j in range(len(values) - 1):
                seg_values = values[j : j + 2]
                seg_angles = angles[j : j + 2]
                seg_color = rainbow_colors[j]
                ax.plot(
                    seg_angles,
                    seg_values,
                    color=seg_color,
                    linewidth=2.5,
                    alpha=0.9,
                    solid_capstyle="round",
                )

            for j in range(len(values) - 1):
                seg_values = values[j : j + 2]
                seg_angles = angles[j : j + 2]
                seg_color = rainbow_colors[j]
                ax.fill(seg_angles, seg_values, color=seg_color, alpha=0.35)

            for j, (angle, value) in enumerate(zip(angles[:-1], dataset["values"])):
                point_hue = (j / n_cats + base_hue) % 1.0
                rgb = colorsys.hsv_to_rgb(point_hue, 1.0, 1.0)
                point_color = f"#{int(rgb[0]*255):02x}{int(rgb[1]*255):02x}{int(rgb[2]*255):02x}"

                star_sizes = [180, 130, 90]
                star_alphas = [0.3, 0.6, 1.0]
                for size, alpha in zip(star_sizes, star_alphas):
                    ax.scatter(
                        [angle],
                        [value],
                        s=size,
                        marker="*",
                        c=[point_color],
                        edgecolors=["#ffffff"] if size == 90 else ["none"],
                        linewidths=1.5 if size == 90 else 0,
                        alpha=alpha,
                        zorder=10,
                    )
