"""Court shooting terrain renderer skill."""

from __future__ import annotations

import matplotlib.pyplot as plt
import numpy as np

from neo_legend.models import RenderRequest, RenderResult
from neo_legend.skills._court import draw_half_court, sample_shots
from neo_legend.skills._plotting import add_canvas, add_reference_footer, create_figure, make_gradient, save_png
from neo_legend.skills.base import BaseLegendSkill, StyleDefinition


class CourtShotSkill(BaseLegendSkill):
    legend_type = "court_shot"
    display_name = "Court Shooting Terrain"
    default_style = "terrain"
    default_size = (1179, 1454)
    style_definitions = (
        StyleDefinition(
            "terrain",
            "Dark half-court shooting terrain with glowing efficiency zones.",
            (
                "6f95be795cc16e2d3b0e0f6425e12353.jpg",
                "542b1ddcb7b0ed0c8748915c4ab50e0a.jpg",
            ),
        ),
        StyleDefinition("hex", "Hex-bin shot profile with red, cream, blue zone colors."),
        StyleDefinition("zone", "Large annotated court zones with soft heat overlays."),
    )

    def render(self, request: RenderRequest) -> RenderResult:
        style = self.resolve_style(request.style)
        width, height = self.output_size(request)
        content = self._render_png(request, style, width, height)
        return self.result(content, style)

    def _render_png(self, request: RenderRequest, style: str, width: int, height: int) -> bytes:
        fig = create_figure(width, height, "#020303")
        canvas = add_canvas(fig)
        title = request.title or "SCOTTIE PIPPEN"
        subtitle = request.subtitle or "1997-98 SHOOTING TERRAIN"

        canvas.text(
            0.5,
            0.905,
            title.upper(),
            color="#f5f4ec",
            fontsize=52,
            fontweight="black",
            ha="center",
            va="center",
        )
        canvas.text(
            0.5,
            0.855,
            subtitle.upper(),
            color="#b7b1b1",
            fontsize=18,
            fontweight="bold",
            ha="center",
            va="center",
        )

        court_ax = fig.add_axes([0.06, 0.06, 0.88, 0.58], facecolor="#020303")
        draw_half_court(court_ax, line_color="#dedbd0", line_width=1.05, alpha=0.62)
        shot_count = int(request.data.get("shot_count", 620))
        seed = int(request.data.get("seed", 11))
        x, y, value = sample_shots(seed=seed, count=shot_count)

        if style == "terrain":
            cmap = make_gradient(["#1e2022", "#57323d", "#c4324c", "#f2a2a1"], "terrain")
            court_ax.hexbin(
                x,
                y,
                C=value,
                reduce_C_function=np.mean,
                gridsize=31,
                extent=(-250, 250, 0, 470),
                mincnt=1,
                cmap=cmap,
                linewidths=0.35,
                edgecolors="#3d3f43",
                alpha=0.9,
            )
            court_ax.scatter(x[::6], y[::6], s=7, color="#f5c0bd", alpha=0.15)
        elif style == "hex":
            cmap = make_gradient(["#4b7cbf", "#f1edd1", "#d51e38"], "shot_hex")
            sizes = np.interp(value, (value.min(), value.max()), (18, 96))
            court_ax.scatter(x, y, c=value, s=sizes, cmap=cmap, marker="h", alpha=0.82, lw=0)
            court_ax.scatter(x[::9], y[::9], s=9, color="#fff4c7", alpha=0.65)
        else:
            self._draw_zones(court_ax, x, y, value)

        if style != "zone":
            for label, px, py in [
                ("51%", -165, 98),
                ("60%", 38, 75),
                ("42%", 178, 260),
                ("31%", -205, 315),
                ("40%", 112, 212),
            ]:
                court_ax.text(px, py, label, color="#f5f4ec", fontsize=14, fontweight="bold")

        add_reference_footer(canvas, "BY @KIRKGOLDSBERRY | GENERATED BY NEO LEGEND")
        return save_png(fig)

    @staticmethod
    def _draw_zones(ax: plt.Axes, x: np.ndarray, y: np.ndarray, value: np.ndarray) -> None:
        rim = np.hypot(x, y - 52.5) < 95
        left = (x < -115) & (y < 315)
        right = (x > 115) & (y < 315)
        arc = (y >= 165) & (np.abs(x) <= 210)

        colors = np.full(len(x), "#3a3d42", dtype=object)
        colors[arc] = "#5b303a"
        colors[left] = "#bd2441"
        colors[right] = "#66a9d1"
        colors[rim] = "#f0b1aa"
        sizes = np.interp(value, (value.min(), value.max()), (18, 72))

        ax.scatter(
            x,
            y,
            s=sizes,
            c=colors,
            marker="h",
            alpha=0.78,
            edgecolors="#27292c",
            linewidths=0.35,
        )
        ax.scatter(x[::8], y[::8], s=7, color="#f8d1cc", alpha=0.22)

        line_color = "#e5ddd1"
        for x_coord in [-220, 220]:
            ax.plot([x_coord, x_coord], [0, 140], color=line_color, lw=1.0, alpha=0.38)
        ax.plot([-220, -82], [140, 188], color=line_color, lw=0.9, alpha=0.38)
        ax.plot([220, 82], [140, 188], color=line_color, lw=0.9, alpha=0.38)
        ax.plot([-80, -80], [0, 190], color=line_color, lw=0.9, alpha=0.42)
        ax.plot([80, 80], [0, 190], color=line_color, lw=0.9, alpha=0.42)

        labels = [
            ("LEFT\n51%", -170, 118, "#d94156"),
            ("RIM\n60%", 0, 78, "#f3b9b1"),
            ("RIGHT\n42%", 170, 118, "#85c8e5"),
            ("ARC\n40%", 0, 255, "#b55f6c"),
            ("CORNER\n31%", -208, 48, "#b1d6e8"),
        ]
        for label, px, py, color in labels:
            ax.text(
                px,
                py,
                label,
                color="#f8f4ed",
                fontsize=12,
                fontweight="bold",
                ha="center",
                va="center",
                bbox={
                    "boxstyle": "round,pad=0.28",
                    "facecolor": color,
                    "edgecolor": "none",
                    "alpha": 0.55,
                },
            )
