"""Rose and donut chart renderer skill."""

from __future__ import annotations

from typing import Any

import matplotlib.pyplot as plt
import numpy as np

from neo_legend.models import RenderRequest, RenderResult
from neo_legend.skills._plotting import add_canvas, cmap_color, create_figure, save_png
from neo_legend.skills.base import BaseLegendSkill, StyleDefinition


class RoseSkill(BaseLegendSkill):
    legend_type = "rose"
    display_name = "Rose Donut Chart"
    default_style = "proposal_comparison"
    default_size = (1179, 1459)
    style_definitions = (
        StyleDefinition(
            "proposal_comparison",
            "Black-background current/proposed lottery donut comparison.",
            ("4acb2531cd2856e6c84dde127fdbb514.jpg",),
        ),
        StyleDefinition("lottery_black", "Single black-background rose donut chart."),
    )

    def render(self, request: RenderRequest) -> RenderResult:
        style = self.resolve_style(request.style)
        width, height = self.output_size(request)
        fig = create_figure(width, height, "#030303")
        canvas = add_canvas(fig)

        canvas.text(
            0.5,
            0.94,
            (request.title or "Lottery Reform").title(),
            color="#f8f7ef",
            fontsize=55,
            fontweight="black",
            ha="center",
        )
        canvas.text(
            0.5,
            0.90,
            request.subtitle or 'Current System Versus "Proposal 1" | Generated by Neo Legend',
            color="#d8d4ce",
            fontsize=17,
            ha="center",
        )

        if style == "lottery_black":
            self._draw_donut(fig, [14, 14, 14, 12, 10, 8, 7, 6, 5, 4, 3, 2, 1], [0.25, 0.28, 0.50, 0.50], "14")
            canvas.text(0.61, 0.56, "Current system", color="#ffffff", fontsize=30, fontweight="black")
        else:
            self._draw_donut(fig, self._current_values(request.data), [0.25, 0.54, 0.42, 0.30], "14")
            self._draw_donut(fig, self._proposed_values(request.data), [0.27, 0.17, 0.40, 0.30], "18")
            canvas.text(0.61, 0.70, "Current system", color="#ffffff", fontsize=30, fontweight="black")
            canvas.text(0.62, 0.48, "14 lottery teams", color="#e7e3dc", fontsize=16)
            canvas.text(0.62, 0.44, "Bottom 3 anchored at 14%", color="#e7e3dc", fontsize=16)
            canvas.text(0.60, 0.38, "Proposed system", color="#ffffff", fontsize=32, fontweight="black")
            canvas.text(0.62, 0.16, "18 lottery teams", color="#e7e3dc", fontsize=16)
            canvas.text(0.62, 0.12, "Bottom 10 flattened to 8%", color="#e7e3dc", fontsize=16)

        self._draw_color_scale(canvas)
        canvas.text(
            0.5,
            0.035,
            "Sources: generated sample data. Replace request.data for production metrics.",
            color="#8f8f8f",
            fontsize=10,
            ha="center",
        )
        return self.result(save_png(fig), style)

    @staticmethod
    def _draw_donut(fig, values: list[float], rect: list[float], center_text: str) -> None:
        ax = fig.add_axes(rect, facecolor="#030303")
        gradient = ["#ff202d", "#ffb12f", "#f6e85a", "#5fd68b", "#55b7f7", "#7377ff"]
        colors = [cmap_color(gradient, i / len(values)) for i in range(len(values))]
        wedges, _ = ax.pie(
            values,
            startangle=90,
            counterclock=False,
            colors=colors,
            wedgeprops={"width": 0.34, "edgecolor": "#030303", "linewidth": 2.2},
        )
        total = sum(values)
        for index, wedge in enumerate(wedges, start=1):
            angle = np.deg2rad((wedge.theta1 + wedge.theta2) / 2)
            label = f"{values[index - 1]:g}%"
            if values[index - 1] <= 4:
                label = str(index)
            ax.text(1.14 * np.cos(angle), 1.14 * np.sin(angle), label, color=colors[index - 1], fontsize=9, ha="center")
        ax.text(0, 0.05, center_text, color="#ffffff", fontsize=30, fontweight="black", ha="center")
        ax.text(0, -0.17, "Lottery Teams", color="#ffffff", fontsize=18, fontweight="bold", ha="center")
        ax.set_aspect("equal")
        ax.set_axis_off()

    @staticmethod
    def _draw_color_scale(canvas) -> None:
        colors = ["#ff202d", "#ff8b24", "#f7d448", "#5fd68b", "#4fb1f0", "#6b7dff"]
        x0, y0, w, h = 0.18, 0.075, 0.64, 0.012
        for index, color in enumerate(colors):
            canvas.add_patch(
                plt.Rectangle((x0 + w * index / len(colors), y0), w / len(colors), h, color=color)
            )
        canvas.text(x0, y0 + 0.03, "Worst record", color="#dcd6cd", fontsize=10, ha="left")
        canvas.text(x0 + w, y0 + 0.03, "Better Records", color="#dcd6cd", fontsize=10, ha="right")

    @staticmethod
    def _current_values(data: dict[str, Any]) -> list[float]:
        values = data.get("current_values")
        default_values = [14, 14, 14, 11.5, 11.5, 9, 6.8, 6.7, 4.5, 3, 2, 1.5, 1, 0.5]
        return values if isinstance(values, list) and values else default_values

    @staticmethod
    def _proposed_values(data: dict[str, Any]) -> list[float]:
        values = data.get("proposed_values")
        default_values = [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]
        return values if isinstance(values, list) and values else default_values
